name: Send notify

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le référentiel
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install beautifulsoup4
          pipx inject beautifulsoup4 requests

      - name: Exécutez le script Python
        run: |
          pipx run beautifulsoup4
          python ntfy.py
        env:
          SECRET_URL: ${{ secrets.SECRET_URL}}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
