name: Update README all day at 00:00

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le référentiel
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --break-system-packages
          pip install beautifulsoup4 requests --break-system-packages

      - name: Exécutez le script Python
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          python main.py

      - name: Commit
        run: |
          git config user.name "MrShadowsWolf"
          git config user.email "loup.thevenin.1@gmail.com"
          git add .
          git commit -m "Mise à jour quotidienne du README"

      - name: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          branch: main
